README.md
The license link is also broken, but the repo doesn't have a top-level LICENSE.
=> Fix contributing link in README.

content/index.md
As noted it also works for Zsh, but the Bash section was in far more need of additions.
=> Add Liquid Prompt to Bash section

content/index.md
* Added above Vim simply due to alphabetical order.
* Removed links to the editor(s) as they were unecessary.
=> Add Emacs section

content/index.md
I've been using this setup to manage my dotfiles for a while and found that it works to my liking very well. I can deploy any set of dotfiles to various Linux and OS X machines with no problem; figured I might as well share it.
=> Add Andrew Schwartzmeyer's dotfiles

content/index.md
Since we now have said section. Also Zsh is canoncially title-cased.
=> Move Liquid Prompt to shells section

CONTRIBUTING.md
We were using the source branch; explicitly state that PRs should be targeted against the master branch now.
Closes #107
=> Be explicit about making PRs to master

index.md
Fixes #121, updates the link to the [sensitive data removal guide](https://help.github.com/articles/remove-sensitive-data/).
=> Update link for sensitive data removal guide

index.md
Hi. Can we add fisherman to the list?
fisherman is a concurrent plugin manager for the fish shell and [plugin ecosystem](https://github.com/fisherman).
**Crosslinks**
* https://github.com/fisherman/fisherman/issues/217
=> Add fisherman https://github.com/fisherman/fisherman to fish section.

index.md
The current link points to the homepage, but I'd rather have it pointing to github repository.
I also added some wording consistency and fixed my own mistake, please squash merge.
=> Fix fisherman link and use correct words in description.

index.md
The link to Mathias Bynens' macOS default script is broken. This commit fixes it.
=> Fix Broken Link

index.md
I am proposing to add my dotfiles to provide a simple straightforward 0-100 macOS bootstrap.
Also worth mentioning is the Makefile. It is providing a fine grained topical control to setup and maintain the project.
The collection aims to re-use as many application defaults as possible. I strive to keep vanilla vim/tmux keybindings with only minimal personal additions where it makes sense or is generally accepted.
This allows me to almost seamlessly switch to systems that do not have my configuration. Plus having fewer specialised additions, the whole setup has turned out to remain highly responsive.
I am happy to be listed in any order you like, idk your policy on this one, I just realised that I put myself on top, but that should not imply my desired order.
Thank you for your …
=> Add Overbryd's dotfiles

index.md
[How to manage dotfiles securely](https://theak.me/blog/how-to-manage-dotfiles.html) is 404, and the base site has a bad SSL cert.
=> Delete link to article that has gone 404

index.md
I wanted to propose adding my dotfiles. I never encountered dotfiles that would feature:
- CI system increasing reproducibility of a system
- Full automation which CI proves and will continue to prove by extending tests coverage
- Dependency management  done via [dependabot](https://dependabot.com/) covering upgrading Python system wide dependencies along with Neovim virtual environments dependencies and used submodules for tools like `pyenv` or `fzf`
hance a decision to try and share with everyone interested that those things are possible :)
=> Add kornicameister's dotfiles

index.md
Remove **How to manage dotfiles securely**  - Seems like entire page is out of picture too.
---
#224 was broken because of this link not being accessible anymore.
=> Remove broken link to abdullah  blog

CONTRIBUTING.md
The link about topic branches in [`CONTRIBUTING.md`](https://github.com/dotfiles/dotfiles.github.com/blame/master/CONTRIBUTING.md#L38) is broken. This PR replaces it with a [working link](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows#_topic_branch).
=> Fix broken link about topic branches

index.md
Figured since [thoughtbot's rcm](https://github.com/thoughtbot/rcm) was [added to the list](https://github.com/dotfiles/dotfiles.github.com/pull/36), their [dotfiles](https://github.com/thoughtbot/dotfiles) should be as well!
=> Add thoughtbot's dotfiles to the list.

index.md
Sorry for spamming PRs. I realized after the previous PR (https://github.com/dotfiles/dotfiles.github.com/pull/250) was merged that the link/highlighting for the Git bare repository tutorial was unhelpful. This moves the linked portion of the text to be more descriptive.
=> Improve highlighting for Git bare repository tutorial

_data/utilities.yml, utilities.md
This PR contains three changes.
1. Allows for non-GitHub websites for utilities. If `website` is provided, that will be the link, otherwise the GitHub URL is used. The GitHub URL is still used for obtaining star counts.
2. Updates the link to use the official website for the tool "yadm".
3. Updates the utilities star counts.
=> Support non repo websites

utilities.md
This PR selects a couple of commits from #283 based on @anishathalye's [suggestion](https://github.com/dotfiles/dotfiles.github.com/pull/283#issuecomment-751372459). It:
* Fixes the comment describing the order of utilities to match the code.
* Orders dotfile utilities with star counts on GitHub ahead of dotfile utilities with no or unknown star counts.
CI will fail, @anishathalye has fixed this in #284, and I'm happy to rebase this PR once #284 is merged.
=> Order utilities by star count, utilities with stars first

_data/utilities.yml
[Dotter](https://github.com/SuperCuber/dotter) is still WIP, ye,t it already supports Windows. This commit proposes adding it to help fellow Windows' users to manage their dotfiles.
=> Add dotter to the list of utilities

_data/frameworks.yml, script/update-star-count.py
The [last update starcount GitHub Action](https://github.com/dotfiles/dotfiles.github.com/actions/runs/1424913012) failed with the message:
```
...
17/31 unixorn/zsh-quickstart-kit -- 457 stars, 67 forks
Traceback (most recent call last):
File "script/update-star-count.py", line 36, in <module>
main()
File "script/update-star-count.py", line 23, in main
repo = g.get_repo(repo_name)
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/github/MainClass.py", line 330, in get_repo
headers, data = self.__requester.requestJsonAndCheck("GET", url)
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
return self.__check(
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/github/Requ …
```
=> Handle deleted repos when updating star counts

.github/PULL_REQUEST_TEMPLATE.md
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```
=> Ugh. Committed double entry during edit

_data/utilities.yml
It contained an incorrect github repo link that prevented star counting.
=> Update dotsecrets entry

_data/inspiration.yml
chezmoi is currently the most popular dotfile manager. This commit adds
the five most popular chezmoi-based dotfile repos, based on GitHub stars
and having the chezmoi tag.
=> Add popular chezmoi-based dotfile repos

inspiration.md
Dotfile utilities are only shown if they have at least 100 stars. Apply
a similar criteria to inspiration.
=> Only show dotfile repos with more than 50 stars in inspiration

_data/utilities.yml
The existing chezmoi compare link seems to be dead as of https://github.com/twpayne/chezmoi/pull/1826/. This PR updates that link.
<table>
<tr>
<td>Dead link
<td>https://github.com/twpayne/chezmoi/blob/master/docs/COMPARISON.md
<tr>
<td>New link
<td>https://www.chezmoi.io/comparison-table/
</table>
---
<details>
<summary>PR Template</summary>
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```
</details>
=> Fix dead link to chezmoi compare 

_data/utilities.yml
The `website` property for Comtrya and chezmoi were not set, meaning that their star counts were not being updated. This PR fixes that.
=> Fix websites for Comtrya and chezmoi

faq.md, tips.md
Github moved some documentation, so update links accordingly
=> Update stale links

_data/utilities.yml
This app is another dotfiles management utility app.  It is written in Go, and it works cross-platform with no dependency except for its binary and optionally git.  One unique feature is that it has symlink mapping for each platform, ie for Mac, Windows, Linux, and Linux-like.
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```
=> Added rhysd/dotfiles CLI app

_data/utilities.yml
I would like to propose adding Symly to the list of utilities.
Symly is a tool helping to centralize sparse file trees. It replicates and maintains a file tree structure of one or more repository layers into a directory by creating symbolic links.
* **Layers**: Symly supports the definition of multiple repositories. Those repositories will be combined in an overriding fashion similar to what is done by OverlayFS.
* **No database**: the filesystem is the state
* **Backup, Sharing, and Synchronization tool of your choice**: Symly replicates the file tree of the repositories inside another file tree using symbolic links. But it doesn’t provide a way to share, synchronize, or back up the content of the repositories. You can then decide to use one or more tools of your choice for this task: …
=> Add symly to the list of utilities

_data/utilities.yml
Mackup is an extremely popular tool for managing settings and configuration for applications. This adds an entry to the "General-purpose dotfile utilities" section.
Closes #172
=> Add Mackup, a settings/config manager

_data/frameworks.yml
Neovim has diverged enough from Vim that it deserves it's own category. Closes #359
=> feat: Add Neovim section under frameworks

.github/workflows/build.yml, .github/workflows/update-star-counts.yml, script/update-star-count.py
- Make `script/update-star-count.py` print malformed data entries so we can tell what data file needs fixing.
- Have separate `run` stepts to make it easier to tell exactly which `yaml` file is bad
- Ignore errors for reddit & twitter urls
- reddit is 404ing legit subreddit urls, probably to keep the AI idiots from scraping them for training data
- twitter is a shitshow, don't let their breakage affect our builds
=> Fix star updater and build actions

_data/bootstrap.yml, _data/frameworks.yml, _data/inspiration.yml, _data/utilities.yml
The star count updating has been broken since #365. This PR fixes it.
It also updates a few URLs for repos that have moved.
=> Fix star count updating and update URLs of moved repos

_data/bootstrap.yml, _data/frameworks.yml
Adds a [dotfiles](https://github.com/mathiasbynens/dotfiles) repository to bootstrap section and [antidote](https://github.com/mattmc3/antidote), which is the successor to Antibody, which was removed in #373.
=> Add entries to bootstrap and Zsh section

_data/frameworks.yml
As seen by in linked PRs, removed projects either haven't been commited to for 9+ years or are archived and no longer maintained.
There are a lot of entries, so I think it is worth narrowing down less-relevant entries.
=> Remove unmaintained and archived Zsh projects

_data/tutorials.yml
This project is a great resource I just found, thanks! 
GNU Stow is mentioned on the site as a possible utility to manage dotfiles, so I thought it'd be good to include this great tutorial I found about how to accomplish that.
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```
=> Add GNU stow tutorial resource

inspiration.md
Based on the [contribution guideline](https://github.com/dotfiles/dotfiles.github.com/blob/master/CONTRIBUTING.md#notability-criteria) there should not be any threshold based on stars. That's why I think it makes sense to remove it. (or update guideline)
Thanks 😉
> ### Notability criteria
> Inspiration: no criteria, sorted by stars
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```
=> Remove `stars` threshold for inspiration (based on guideline)

_data/utilities.yml
Multigit allows multiple git repositories to be overlaid in the same directory, useful for projects with separately developed components. Unlike submodules or subtrees, it tracks files from any part of the directory structure, acting like a union filesystem where each repository is a layer.
-  This document is covered by the [MIT License](https://github.com/dotfiles/dotfiles.github.com/blob/master/LICENSE.md), and I agree to contribute this PR under the terms of the license
=> Added Multigit

_data/frameworks.yml, _data/utilities.yml
Add the LazyVim and AstroNvim distributions, which are popular enough to warrant inclusion in this repository.
Also added back the website for Comtrya, as it is online again.
=> Add more Neovim distributions
