index.html

Render  #70, #71, #72 & #73 into upstream.

Merge #70, #71, #72 & #73

---

content/index.md

Per @twe4ked's comment on #73, made new Shells and Editors section headings

Add Shells and Editors section headings

---

content/index.md

* Add @ashishb's dotfiles - Closes #37 
* Add tutorials section with Lars Kappert's medium article suggested by @intergalactic-overlords - closes #43

Add to dotfiles and add tutorials section

---

index.html

* Add @ashishb's dotfiles - Closes #37
* Add tutorials section with Lars Kappert's medium article suggested by @intergalactic-overlords - closes #43

Render changes from #77 to master branch

---

index.html

Render merged #79 & publish to master.

Render merged #79

---

content/index.md

[Neobundle](https://github.com/Shougo/neobundle.vim) is a modern plugin manager. It has it place in this website. But feel free to discuss about it.

Add Neobundle to Vim configuration

---

index.html

Publish latest approved PR to website.

Render PR #81 to website

---

content/index.md

* Add entries for dotfiles, dotsync & dotvim
* Fix sorting

Add dotphiles, dotsync & dotvim. Closes #14

---

content/index.md

* List shells in alphabetical order.
* List tools in the utilities section in alphabetical order
* Update Zgen description
* List emacs resources in alphabetical order

Misc cleanups.

---

content/index.md

It may be worth including [this guide](http://www.anishathalye.com/2014/08/03/managing-your-dotfiles/) -- it covers material that complements Lars's tutorial, explaining the philosophy behind dotfiles and shows organizational approaches, installation/bootstrapping tools, and general tips and tricks.
(and probably partially addresses #30)

Add link to dotfiles management guide

---

index.html

Render to master, publish to site

Add Steve Francia's Vim distribution

---

index.md

@nwinkler, I redit your commit on the master branch after @twe4ked's update to use jekyll.
Thanks for the contribution!

Redo PR #99 on master now that we've update to jekyll

---

index.md

Add links to Wes Bos' videos and to dotfiler

---

index.md

Adding an entry for the Homemaker dotfile management utility.

Adding entry about Homemaker utility

---

content/index.md

Added my personal node bootstrapping tool to the list of bootstraps.
@jh3y

Added jh3y's kody to bootstraps

---

index.md

This seems like a good place to put this resource (to get started). Feel free to move it, though,

Add awesome-dotfiles

---

index.md

Requesting addition of Alterant to dotfile utilities.

Add Alterant dotfile utility

---

index.md

fix oh-my-fish link

---

index.md

See http://blog.dictionary.com/farther-further/

farther -> further

---

.travis.yml

This travis configuration will automatically check the links in index.md on new pull requests.

Have travis check the links in index.md and README.md

---

index.md

Update for consistency, add link to fish home page.

Update fisherman entry

---

index.md

Dries Vints created some quality .dotfiles content that deserves a place on this page.

Add Dries Vints' dotfiles and blog post

---

index.md

Custom Zsh and Terminal/iTerm themes and useful aliases for web developers, etc.

Add Artem Sapegin’s dotfiles

---

index.md

My attempt to automate developer's environment.

Add Nick Plekhanov’s dotfiles

---

index.md

Also sync some changes that had ended up in my fork instead of origin.

Remove broken branchable com link

---

index.md

This tool has a website now, instead of just the GitHub landing page.

Update URL for yadm

---

index.md

I wrote a post in 2012 detailing how to use Git and Github to manage your dotfiles. It's the most popular post on my blog, and my dotfiles repo has also been very popular. I thought it'd be good to add it to the list of tutorials.

Update index.md to include my blog post from 2012

---

index.md

Hello, my dotfiles could be a good reference to other developers :)
It covers many CLI commands(vim, neovim, zsh, bash, tmux, screen, ctags, wget, curl, git and more) and GUI X environments!

Add posquit0's dotfiles example

---

index.md

https://github.com/Kraymer/F-dotfiles

Addef F-dotfiles

---

index.md

index.md: fix typo

---

_layouts/default.html
index.md

I noticed a couple of issues with outdated github repo addresses and I fixed in order to avoid unnecessary URL redirections.  
Also I took advantage to fix minor html inconsistencies with some other links.
It is my pleasure to contribute for this awesome project!

Update github repo adresses, fix html inconsistencies

---

index.md

Hi! I created a dotfile management utility called Homely. It has some unique advantages over other dotfile management utilities (python scripting, automatic cleanup) and I think it'd make a great addition the utilities already listed on your site.

Add link to Homely dotfile management utility

---

_layouts/default.html
_sass/_minimal.sass
stylesheets/styles.sass

- Improve readability:
- Adjust text colors to more dark color tones to make them visible
- Increase font size for body
- Increase font weight for body and links
- Increase line height of headers
- Add margin-bottom between list items
- Adjust margins for headers
- Document appears to be written in English. Add `lang="en"` (or variant) to the `<html>` start tag.
- Allow user to adjust page scale on a mobile devices (for better accessibility)

Readability improvements to CSS styles

---

README.md
index.md

-Replace OS X with macOS
-Made explicit HTTPS calls
-Update missing links

Update website and docs

---

index.md

Recently moved my blog to Medium.

Update link for blogpost

---

index.md

Hi,
I've been using this for a few days, seems pretty solid. I think it should be on this list.

Add toasty-zsh

---

index.md

dotfiles for Bash (Linux) / ZSH (Linux) / Git Bash (Windows) / Cygwin (Windows) / Bash on Ubuntu on Windows
PS: Happy coding @ all!

add dotfiles (with support for windows + linux)

---

stylesheets/styles.sass

[Before](https://i.imgur.com/6U4LQs2.png) and [after](https://i.imgur.com/LtbOmca.png) adding the 400 and 400 italic Lato fonts.

Improve the readability a lot, by adding 400 Lato and 400 Italic Lato to the fonts

---

index.md

Cleaned up the sorting in subsections.

Sort subsections

---

index.md

I'd like to share my dev-env configuration that I've used and tweaked for years. It has everything needed to setup a new development machine, including settings for homebrew, tmux, neovim, zsh, global JS dependencies, and is preconfigured to sync iTerm2 settings.

Add volny's dotfiles

---

index.md

Adding my dotfiles to the list.

Add my (Jonas Devlieghere's) dotfiles.

---

index.md

I really like reading others people dotfiles and learn tricks from them. I hope others can learn from mine.

Add Nelson Estevão's dotfiles

---

index.md

- Antibody is a plugin manager for Zsh.
- Bonclay is a dotfiles manager.

add Antibody and Bonclay

---

index.md

Dotfiles are meant to be shared lmao

Add Huy Vo's dotfiles

---

index.md

Add jbwyatt4's Chef Dotfile Manager

---

index.md

Update Ashish Bhatia's dotfiles description to add cryptocurrencies to it

Update Ashish Bhatia's dotfile description

---

index.md

Make capitalization consistent throughout

Make ZSH capitalization consistent

---

index.md

fixes #198 -- new version out now.

adding link to yadoma

---

index.md

Adding link to bashdot management framework.
https://github.com/weavenet/bashdot

adding bashdot

---

index.md

Minor wording tweak in tutorials section

Wording tweak

---

index.md

url updated

---

index.md

Just wanted to submit my contribution.

Added my Dotfiles repo to the list.

---

index.md

I've recently decided to host my content on my own website again. The one on my website is also up to date with the latest changes to the repo.

Change link to personal website

---

index.md

I've learned quite a bit from others' dotfiles and I'd love to contribute my share!

added aeolyus's dotfiles

---

index.md

Maybe it'll be interesting for someone

add cristianpb's dotfiles

---

index.md

Add @eirenicon's bspwm article

---

index.md

Added myself.
Signed-off-by: Kamil Zabielski <kamil.zabielski@sysdogs.com>

Add limakzi

---

index.md

Added post back after I have moved my website to github.

added post for encrypted dotfiles

---

index.md

I've taken a lot of care in putting together my dotfiles (which can be easily installed with stow). I hope that you will consider adding my repo to your collection. Thank you.

Add Ace Cassidy's dotfiles

---

index.md

I made a dotfiler manager that combined the best of the rest.

Add CGamesPlay/dfm

---

index.md

https://github.com/dotfiles/dotfiles.github.com/issues/135
Added a link under `Tutorials` for managing dotfiles using a Git bare repository. I use this technique to manage my own dotfiles and think it this tutorial be super helpful to anyone reading through this site.

Recommend tutorial on Git bare repository management

---

tips.md

Add tip about how I use multiple branches to share configuration between mac and linux.

Add tip about multiple branches

---

_data/tutorials.yml

Fix bad link to abdullah.today

Fix 404 link

---

_data/inspiration.yml

Adding my own newly created dotfiles
https://github.com/jogendra/dotfiles

Add Jogendra's dotfiles

---

_data/inspiration.yml

First of all, thanks for offering this absolutely great dotfiles resource, it really adds to the community.
Having the ability to open a PR to contribute to the inspiration list was a great idea! I'm here to add my entry to the list, hoping that it inspires someone as much as the current entries have inspired me.
Thanks in advance!

Add rogerluan/dotfiles inspiration.

---

_data/inspiration.yml

Hello,
I'm adding my personal dotfiles repository, since it includes a different approach that I haven't seen in the other ones listed. An automatic configurator using Ansible.
Thanks.

Add Mateus Revoredo dotfiles

---

_data/bootstrap.yml
_data/frameworks.yml
_data/inspiration.yml
_data/utilities.yml

Prompted by #273 
Is there any nice way we can automate this, so that the star counts are updated, say, once a month?
@unixorn thoughts? I'd be happy to write a simple bot for this.

Update star counts

---

_data/inspiration.yml

Add Angelo Dini's dotfiles

---

_data/inspiration.yml

Aesthetic OpenboxWM Environment. The complete setup, including configuration of several apps and bash scripting allows things to change with just one click and from the variables.
**Thanks!**

Add owl4ce's dotfiles

---

_data/tutorials.yml

Add to list of tutorials: https://drewdevault.com/2019/12/30/dotfiles.html

Add DrewDeVault's tutorial

---

_data/frameworks.yml
_data/utilities.yml

[Sheldon](https://github.com/rossmacarthur/sheldon) is a fast, configurable, shell plugin manager

Add sheldon to the list of utilities

---

_data/frameworks.yml

Add missing category to sheldon

Add a category to sheldon

---

_data/utilities.yml

Add jbernard/dotfiles to utilities
Also available on PyPI at https://pypi.org/project/dotfiles/

Add jbernard/dotfiles to utilities

---

_data/inspiration.yml

This is my personal configuration for macOS & Linux with configs for everyday applications.
https://github.com/exshak/dotfiles

Add exshak's dotfiles

---

_data/frameworks.yml

Add Doom Emacs

---

_data/frameworks.yml

Add zgenom entry and deprecate zgen in favor of it.
Signed-off-by: Joe Block <jpb@unixorn.net>

Add zgenom

---

_data/tutorials.yml

Update canonical link of "Getting Started With Dotfiles"
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Update href for "Getting Started" tutorial

---

_data/inspiration.yml
_data/utilities.yml

This PR adds comtrya, updates chezmoi's description and links, and adds a few more popular dotfile repos (all >= 50 GitHub stars).

Add comtrya, popular repos, and update chezmoi links

---

tips.md

Adds gitignore.io to the tips page #324.

---

_data/inspiration.yml

**Hi!** I just changed my [dotfiles](https://github.com/owl4ce/dotfiles) notes since it changed now, I know that "very" small changes like this are not allowed (?) as it says on [CONTRIBUTING.md](https://github.com/dotfiles/dotfiles.github.com/blob/master/CONTRIBUTING.md#contributing). However, please consider to merge.
**Thank you!**
```
Congrats! Now owl4ce's dotfiles uses POSIX-compliant sh instead of bash.
```
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Update owl4ce's dotfiles notes

---

_data/frameworks.yml

Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Update zsh quickstart and awesome-zsh-plugins entries

---

_data/utilities.yml

Thanks a lot for listing [dotdrop](https://github.com/deadc0de6/dotdrop). This PR updates the description.

update dotdrop description

---

_data/inspiration.yml

inspiration: Add liskin/dotfiles

---

_data/inspiration.yml

Adding my Ansible based dotfiles:
- Well maintained (repository exists since 8 years, more than 800 commits)
- Documented as much as possible so it should be quite easy for beginners even if they don't have any Ansible experience
- Takes care zsh configuration, Homebrew/Cask formulas, npm/gem/pip packages, Mac App Store apps, macOS defaults, Docker pruning, VIM configuration and more
iTerm | Visual Studio Code
--- | ---
[![](https://asciinema.org/a/cPPgWS3Ju2twoyl7U5UfFYOYI.svg)](https://asciinema.org/a/cPPgWS3Ju2twoyl7U5UfFYOYI) <center></center> | ![](https://i.imgur.com/abpdBUY.png)
---
https://github.com/frdmn/dotfiles

Add frdmn's dotfiles

---

_data/frameworks.yml

Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Add Starship Prompt to the list of Shell frameworks

---

_data/inspiration.yml

---
I added my dotfiles to inspiration. My dotfiles is for Windows GitBash, WSL, Ubuntu, MacOS by single `.bashrc` file.

Add Neos21's Dotfiles To Inspiration

---

.github/PULL_REQUEST_TEMPLATE.md
faq.md
index.md

- Add link to r/dotfiles
- Remove old maintainer's twitter from `faq.md`
Closes #339
Signed-off-by: Joe Block <jpb@unixorn.net>
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Add link to r/dotfiles

---

_data/inspiration.yml

This PR adds my humble dotfiles repository as a potential inspiration for others.

feat: add karras dotfiles repository to inspiration

---

.github/workflows/build.yml

actions/setup-ruby is deprecated

Switch to ruby/setup-ruby and pin version

---

_data/inspiration.yml

https://github.com/yutkat/dotfiles

Add yutkat's dotfiles

---

_data/inspiration.yml

https://github.com/codingjerk/dotfiles

Add codingjerk's dotfiles

---

_data/tutorials.yml

`abdullah.today` is not responding, remove
Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Abdullah.today is not responding to https

---

CONTRIBUTING.md

Simply updates the formatting of the CONTRIBUTING file to be in line with all other markdown files in this repository.

chore: Improve formatting of `CONTRIBUTING.md`

---

_data/bootstrap.yml

add dorothy to boostrap (close #363)

---

_data/inspiration.yml

My dotfiles have changed a lot since the time I had last added them here, I wanted to update the link and also include some other extenstions for it here.

Update 2KAbhishek's Dotfiles section

---

_data/inspiration.yml

Valid:
```yaml
```
Invalid:
```yaml
foo: bar: baz
```

Add `pivoshenko/dotfiles`

---

_data/inspiration.yml

Just updating my repos description. I've been on the site for a long time.

feat(inspo): update xero's description

---

_data/inspiration.yml

Add my dotfiles to inspo, because I read a bunch of these to make mine!

Add `Skenvy/dotfiles`

---

_data/utilities.yml

Fixes the error introduced in #388.

Fix structure of _data/utilities.yaml
